#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export MODEL_NAME=${MODEL_NAME:-afm_45b}
export NUM_LAYERS=${NUM_LAYERS:-36}
export HIDDEN_SIZE=${HIDDEN_SIZE:-2560}
export NUM_HEADS=${NUM_HEADS:-20}
export FFN_HIDDEN_SIZE=${FFN_HIDDEN_SIZE:-18432}
export KV_CHANNELS=${KV_CHANNELS:-128}
export NUM_QUERY_GROUPS=${NUM_QUERY_GROUPS:-4}
export SEQ_LENGTH=${SEQ_LENGTH:-256}
export MAX_POSITION_EMBEDDINGS=${MAX_POSITION_EMBEDDINGS:-65536}
export VOCAB_SIZE=${VOCAB_SIZE:-7808}
export MAKE_VOCAB_SIZE_DIVISIBLE_BY=${MAKE_VOCAB_SIZE_DIVISIBLE_BY:-1}
export NORMALIZATION=${NORMALIZATION:-RMSNorm}
export NORM_EPSILON=${NORM_EPSILON:-1e-5}
export ROTARY_BASE=${ROTARY_BASE:-10000}
export ROTARY_PERCENT=${ROTARY_PERCENT:-1.0}
export ACTIVATION=${ACTIVATION:-squared_relu}
export UNTIE_EMBEDDINGS=${UNTIE_EMBEDDINGS:-1}

exec bash "${SCRIPT_DIR}/train_qwen3_4b_tp_dp_byteps.sh" "$@"
