#!/bin/bash

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export MODEL_NAME=${MODEL_NAME:-minitron_4b}
export NUM_LAYERS=${NUM_LAYERS:-32}
export HIDDEN_SIZE=${HIDDEN_SIZE:-3072}
export NUM_HEADS=${NUM_HEADS:-24}
export FFN_HIDDEN_SIZE=${FFN_HIDDEN_SIZE:-9216}
export KV_CHANNELS=${KV_CHANNELS:-128}
export NUM_QUERY_GROUPS=${NUM_QUERY_GROUPS:-8}
export SEQ_LENGTH=${SEQ_LENGTH:-256}
export MAX_POSITION_EMBEDDINGS=${MAX_POSITION_EMBEDDINGS:-4096}
export VOCAB_SIZE=${VOCAB_SIZE:-4224}
export NORMALIZATION=${NORMALIZATION:-LayerNorm}
export NORM_EPSILON=${NORM_EPSILON:-1e-5}
export ROTARY_BASE=${ROTARY_BASE:-10000}
export ROTARY_PERCENT=${ROTARY_PERCENT:-0.5}
export ACTIVATION=${ACTIVATION:-squared_relu}
export UNTIE_EMBEDDINGS=${UNTIE_EMBEDDINGS:-1}
export APPLY_LAYERNORM_1P=${APPLY_LAYERNORM_1P:-1}

exec bash "${SCRIPT_DIR}/train_qwen3_4b_tp_dp_byteps.sh" "$@"
